apiVersion: v1
kind: ConfigMap
metadata:
  name: notifications-service-config
data:
  NOTIFICATIONS_DB_URL: {{ .Values.config.dbUrl | quote }}
  NOTIFICATIONS_DB_USER: {{ .Values.config.dbUser | quote }}
  BANK_KAFKA_BOOTSTRAP_SERVERS: {{ .Values.config.kafkaBootstrapServers | quote }}
  BANK_NOTIFICATIONS_TOPIC: {{ .Values.config.notificationsTopic | quote }}
  BANK_NOTIFICATIONS_GROUP: {{ .Values.config.consumerGroup | quote }}
