apiVersion: v1
kind: ConfigMap
metadata:
  name: notifications-service-config
data:
  SERVER_PORT: {{ .Values.config.serverPort | quote }}
  NOTIFICATIONS_DB_URL: {{ .Values.config.dbUrl | quote }}
  NOTIFICATIONS_DB_USER: {{ .Values.config.dbUser | quote }}
  BANK_JWK_SET_URI: {{ .Values.config.jwkSetUri | quote }}
