apiVersion: v1
kind: ServiceAccount
metadata:
  name: notifications-service-test
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: notifications-service-test
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: notifications-service-test
subjects:
  - kind: ServiceAccount
    name: notifications-service-test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: notifications-service-test
