server:
  port: ${SERVER_PORT:8082}

spring:
  application:
    name: cash-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${BANK_JWK_SET_URI:http://localhost:9090/realms/my-bank/protocol/openid-connect/certs}
      client:
        provider:
          keycloak:
            token-uri: ${BANK_TOKEN_URI:http://localhost:9090/realms/my-bank/protocol/openid-connect/token}
        registration:
          bank-service:
            provider: keycloak
            client-id: ${CASH_CLIENT_ID:cash-service}
            client-secret: ${CASH_CLIENT_SECRET:cash-secret}
            authorization-grant-type: client_credentials

resilience4j:
  circuitbreaker:
    instances:
      accounts:
        sliding-window-size: 5
        failure-rate-threshold: 50
      notifications:
        sliding-window-size: 5
        failure-rate-threshold: 50

management:
  endpoints:
    web:
      exposure:
        include: health,info
