replicaCount: 1

image:
  repository: transfer-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8083

config:
  serverPort: "8083"
  accountsUrl: "http://accounts-service:8081"
  jwkSetUri: "http://keycloak:8080/realms/my-bank/protocol/openid-connect/certs"
  tokenUri: "http://keycloak:8080/realms/my-bank/protocol/openid-connect/token"
  clientId: "transfer-service"
  kafkaBootstrapServers: "kafka:9092"
  notificationsTopic: "bank.notifications"

secret:
  clientSecret: "transfer-secret"

probes:
  readiness:
    path: "/actuator/health"
    initialDelaySeconds: 20
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
  liveness:
    path: "/actuator/health"
    initialDelaySeconds: 40
    periodSeconds: 20
    timeoutSeconds: 5
    failureThreshold: 3

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"
