apiVersion: v1
kind: Service
metadata:
  name: accounts-postgres
spec:
  type: {{ .Values.service.type }}
  selector:
    app: accounts-postgres
  ports:
    - name: postgres
      port: {{ .Values.service.port }}
      targetPort: postgres
