gateway-service:
  service:
    nodePort: 30080

keycloak:
  service:
    nodePort: 30090

accounts-postgres:
  persistence:
    size: 1Gi

notifications-postgres:
  persistence:
    size: 1Gi

kafka:
  persistence:
    size: 2Gi
