apiVersion: v1
kind: ConfigMap
metadata:
  name: cash-service-config
data:
  SERVER_PORT: {{ .Values.config.serverPort | quote }}
  BANK_ACCOUNTS_URL: {{ .Values.config.accountsUrl | quote }}
  BANK_JWK_SET_URI: {{ .Values.config.jwkSetUri | quote }}
  BANK_TOKEN_URI: {{ .Values.config.tokenUri | quote }}
  CASH_CLIENT_ID: {{ .Values.config.clientId | quote }}
  BANK_KAFKA_BOOTSTRAP_SERVERS: {{ .Values.config.kafkaBootstrapServers | quote }}
  BANK_NOTIFICATIONS_TOPIC: {{ .Values.config.notificationsTopic | quote }}
  BANK_ZIPKIN_ENDPOINT: {{ .Values.config.zipkinEndpoint | quote }}
  BANK_LOGSTASH_HOST: {{ .Values.config.logstashHost | quote }}
  BANK_LOGSTASH_PORT: {{ .Values.config.logstashPort | quote }}
