apiVersion: v1
kind: Service
metadata:
  name: cash-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: cash-service
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
