apiVersion: v1
kind: Service
metadata:
  name: zipkin
spec:
  type: {{ .Values.service.type }}
  selector:
    app: zipkin
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
{{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
{{- end }}
