server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: accounts-service
  datasource:
    url: ${ACCOUNTS_DB_URL:jdbc:postgresql://localhost:5432/bank}
    username: ${ACCOUNTS_DB_USER:bank}
    password: ${ACCOUNTS_DB_PASSWORD:bank}
  flyway:
    schemas: accounts
    default-schema: accounts
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: accounts
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${BANK_JWK_SET_URI:http://localhost:9090/realms/my-bank/protocol/openid-connect/certs}
      client:
        provider:
          keycloak:
            token-uri: ${BANK_TOKEN_URI:http://localhost:9090/realms/my-bank/protocol/openid-connect/token}
        registration:
          bank-service:
            provider: keycloak
            client-id: ${ACCOUNTS_CLIENT_ID:accounts-service}
            client-secret: ${ACCOUNTS_CLIENT_SECRET:accounts-secret}
            authorization-grant-type: client_credentials

resilience4j:
  circuitbreaker:
    instances:
      notifications:
        sliding-window-size: 5
        failure-rate-threshold: 50

management:
  endpoints:
    web:
      exposure:
        include: health,info
