apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: ELASTICSEARCH_HOSTS
              value: {{ .Values.config.elasticsearchHosts | quote }}
            - name: SERVER_PUBLICBASEURL
              value: {{ .Values.config.publicBaseUrl | quote }}
            - name: XPACK_SECURITY_ENABLED
              value: "false"
            - name: XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY
              value: "my-bank-kibana-observability-key-123456"
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
          readinessProbe:
            httpGet:
              path: /api/status
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 12
          livenessProbe:
            httpGet:
              path: /api/status
              port: http
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 6
          resources:
{{ toYaml .Values.resources | indent 12 }}
