apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-service-config
data:
  SERVER_PORT: {{ .Values.config.serverPort | quote }}
  BANK_ACCOUNTS_URL: {{ .Values.config.accountsUrl | quote }}
  BANK_CASH_URL: {{ .Values.config.cashUrl | quote }}
  BANK_TRANSFER_URL: {{ .Values.config.transferUrl | quote }}
  BANK_JWK_SET_URI: {{ .Values.config.jwkSetUri | quote }}
  BANK_ZIPKIN_ENDPOINT: {{ .Values.config.zipkinEndpoint | quote }}
  BANK_LOGSTASH_HOST: {{ .Values.config.logstashHost | quote }}
  BANK_LOGSTASH_PORT: {{ .Values.config.logstashPort | quote }}
