bank:
  security:
    issuer-uri: ${BANK_ISSUER_URI:http://localhost:9090/realms/my-bank}
    jwk-set-uri: ${BANK_JWK_SET_URI:http://localhost:9090/realms/my-bank/protocol/openid-connect/certs}
    token-uri: ${BANK_TOKEN_URI:http://localhost:9090/realms/my-bank/protocol/openid-connect/token}

management:
  endpoint:
    health:
      probes:
        enabled: true
