replicaCount: 1

image:
  repository: gateway-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8090
  nodePort: 30080

config:
  serverPort: "8090"
  accountsUrl: "http://accounts-service:8081"
  cashUrl: "http://cash-service:8082"
  transferUrl: "http://transfer-service:8083"
  jwkSetUri: "http://keycloak:8080/realms/my-bank/protocol/openid-connect/certs"

probes:
  readiness:
    path: "/actuator/health"
    initialDelaySeconds: 20
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
  liveness:
    path: "/actuator/health"
    initialDelaySeconds: 40
    periodSeconds: 20
    timeoutSeconds: 5
    failureThreshold: 3

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"
